### ISSUE TITLE
python3 rsf.py 

### ISSUE THREAD

**Issue by bennova5** [threat9/routersploit#774]
Traceback (most recent call last):
  File "/home/bennova/routersploit/rsf.py", line 10, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/home/bennova/routersploit/routersploit/interpreter.py", line 12, in <module>
    from future.builtins import input
ModuleNotFoundError: No module named 'future'

**Comment by Temuxuser2021** [comment]
pip3 install future 


Then it will automatically start
