### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by bennova5** [threat9/routersploit#778]
Traceback (most recent call last):
  File "/home/bennova/Desktop/routersploit/rsf.py", line 10, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/home/bennova/Desktop/routersploit/routersploit/interpreter.py", line 12, in <module>
    from future.builtins import input
ModuleNotFoundError: No module named 'future'

**Comment by bennova5** [comment]
my ios is kali linux can some body help me my
